apiVersion: v1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
  labels:
    service: helloworld-go
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: helloworld-go
  type: LoadBalancer
