name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image and publish to Github package
      run: |
        VERSION=$(date +%s)
        docker build . --file Dockerfile --tag docker.pkg.github.com/${GITHUB_ACTOR}/helloworld-go/app:${VERSION}
        docker login docker.pkg.github.com --username ${GITHUB_ACTOR} --password-stdin
        docker push docker.pkg.github.com/${GITHUB_ACTOR}/helloworld-go/app:${VERSION}
        
