name: Secret scan

on: push

jobs:
  secret-scan:
    name: Secrets Scan
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - name: trufflehog-actions-scan
        uses: edplato/trufflehog-actions-scan@master
